<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-23T16:18:34 IST" name="Default suite" finished-at="2024-08-23T16:18:49 IST" duration-ms="15484">
    <groups>
    </groups>
    <test started-at="2024-08-23T16:18:34 IST" name="Default test" finished-at="2024-08-23T16:18:49 IST" duration-ms="15484">
      <class name="testNG.ListenerTestCaseClass">
        <test-method is-config="true" signature="setUpMethod()[pri:0, instance:testNG.ListenerTestCaseClass@233795b6]" started-at="2024-08-23T16:18:34 IST" name="setUpMethod" finished-at="2024-08-23T16:18:43 IST" duration-ms="9165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpMethod -->
        <test-method signature="passMethod()[pri:0, instance:testNG.ListenerTestCaseClass@233795b6]" started-at="2024-08-23T16:18:43 IST" name="passMethod" finished-at="2024-08-23T16:18:49 IST" duration-ms="6077" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passMethod -->
        <test-method signature="failMethod()[pri:1, instance:testNG.ListenerTestCaseClass@233795b6]" started-at="2024-08-23T16:18:49 IST" name="failMethod" finished-at="2024-08-23T16:18:49 IST" duration-ms="36" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The element text is not matching expected [Detect again] but found [Detect Again]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The element text is not matching expected [Detect again] but found [Detect Again]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testNG.ListenerTestCaseClass.failMethod(ListenerTestCaseClass.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failMethod -->
        <test-method signature="skipMethod()[pri:2, instance:testNG.ListenerTestCaseClass@233795b6]" started-at="2024-08-23T16:18:49 IST" name="skipMethod" finished-at="2024-08-23T16:18:49 IST" depends-on-methods="testNG.ListenerTestCaseClass.failMethod" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testNG.ListenerTestCaseClass.skipMethod() on instance testNG.ListenerTestCaseClass@233795b6 depends on not successfully finished methods 
[testNG.ListenerTestCaseClass.failMethod() on instance testNG.ListenerTestCaseClass@233795b6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testNG.ListenerTestCaseClass.skipMethod() on instance testNG.ListenerTestCaseClass@233795b6 depends on not successfully finished methods 
[testNG.ListenerTestCaseClass.failMethod() on instance testNG.ListenerTestCaseClass@233795b6]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skipMethod -->
        <test-method is-config="true" signature="tearDownMethod()[pri:0, instance:testNG.ListenerTestCaseClass@233795b6]" started-at="2024-08-23T16:18:49 IST" name="tearDownMethod" finished-at="2024-08-23T16:18:49 IST" duration-ms="138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
      </class> <!-- testNG.ListenerTestCaseClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
